package exceptionTest;

import java.util.Scanner;

public class ExceptionTest01 {
	public static void main(String[] args) {
		System.out.println("프로그램 시작");
		
		Scanner sc = new Scanner(System.in);
		int num1 = sc.nextInt(), num2 = sc.nextInt(), result = 0;
		if(num2 == 0) {
			System.out.println("0으로는 나눌수없습니다");
		}else{
			result = num1 / num2;
		}
		System.out.println(result);
		
		System.out.println("프로그램 종료");
	}
}
